### ISSUE TITLE
Chem Viewer is cut off by UI Context canvas

### ISSUE THREAD

**Issue by ck-cklinger** [partridgejiang/Kekule-React#3]
Hi @partridgejiang, I'm having an issue where the rendered component is essentially "split in half" and some of the structure gets hidden:

![Screenshot 2024-08-05 at 3 05 22 PM](https://github.com/user-attachments/assets/dc69cbd7-37fb-43e6-bc46-05fc88ebe6c6)

What I end up with is a 300x300 component window, but with two 300x150 canvases, the first is for "K-Chem-Displayer-DrawContext" and the other is for "K-Chem-Viewer-UIContext".

This is a wrapped version of the Viewer widget, i.e., created by calling:

`const Viewer = KekuleReact.Utils.wrapWidget(Kekule.ChemWidget.Viewer, {
    exposeWidgetEvents: true,
    exposeWidgetPropertiesToReactProps: true,
});`

I don't need any UI here and so I've disabled it every way I can think of (by passing props, by getting a ref to the underlying widget and calling `setEnableEdit` and `setEnableToolbar` to false, by setting the predefined setting to static, etc.). 

Is there any way to only show the displayer and not the UI context?

**Comment by partridgejiang** [comment]
Hi @ck-cklinger. Quite sorry for noticing the issue till today. Does the default theme of Kekule by imported? Without it, the viewer (and other widgets) may not be properly displayed. Please try to add a new ```import``` in your source:
```js
import 'kekule/theme';
```
To disable the child UI components, just setting the predefined setting to static.

**Comment by ck-cklinger** [comment]
@partridgejiang no worries at all, thank you for taking the time to reply! Yes, importing the theme fixed my problem and the structures now display as I was hoping they would.

Thanks for your help!

**Comment by ck-cklinger** [comment]
@partridgejiang no worries at all, thank you for taking the time to reply! Yes, importing the theme fixed my problem and the structures now display as I was hoping they would.

Thanks for your help!
